import { motion } from "framer-motion";

function DashboardPreview() {
  return (
    <section
  id="demo"
  className="
  relative
  bg-black
  text-white
  py-40
  overflow-hidden
  "
>
      {/* Background Glow */}
      <div
        className="
        absolute
        inset-0
        bg-red-500/5
        blur-[200px]
        "
      />

      <div className="max-w-7xl mx-auto px-10 relative z-10">

        <h2
          className="
          text-7xl
          lg:text-8xl
          font-light
          leading-none
          "
        >
          From field data
          <br />

          <span className="italic text-red-500">
            to city foresight.
          </span>
        </h2>

        <div className="grid lg:grid-cols-2 gap-20 mt-24">

          {/* LEFT */}

          <div>

            <p className="text-gray-400 text-xl mb-10">
              Every signal generated by your city
              becomes actionable intelligence.
            </p>

            <div className="space-y-8">

              <div className="border-b border-white/10 pb-6">
                Traffic Cameras
              </div>

              <div className="border-b border-white/10 pb-6">
                Hospital Systems
              </div>

              <div className="border-b border-white/10 pb-6">
                Citizen Reports
              </div>

              <div className="border-b border-white/10 pb-6">
                Weather Intelligence
              </div>

            </div>

          </div>

          {/* RIGHT */}

          <div className="relative h-[500px]">

            {/* Card 1 */}

            <motion.div
              animate={{ y: [0, -15, 0] }}
              transition={{
                repeat: Infinity,
                duration: 5
              }}
              className="
              absolute
              top-0
              right-0
              w-80
              bg-black/70
              backdrop-blur-xl
              border
              border-green-500/20
              rounded-3xl
              p-8
              "
            >
              <p className="text-green-400 text-sm">
                PROJECT FORECAST
              </p>

              <h3 className="text-6xl mt-4">
                94%
              </h3>

              <p className="text-gray-500 mt-4">
                On-time delivery prediction
              </p>
            </motion.div>

            {/* Card 2 */}

            <motion.div
              animate={{ y: [0, 15, 0] }}
              transition={{
                repeat: Infinity,
                duration: 6
              }}
              className="
              absolute
              left-0
              top-40
              w-72
              bg-black/70
              backdrop-blur-xl
              border
              border-red-500/20
              rounded-3xl
              p-8
              "
            >
              <p className="text-red-400">
                RECOMMENDATION
              </p>

              <h3 className="text-2xl mt-4">
                Re-route traffic corridor
              </h3>

              <p className="text-gray-500 mt-3">
                Saves 4.2 hours daily
              </p>
            </motion.div>

            {/* Card 3 */}

            <motion.div
              animate={{ y: [0, -10, 0] }}
              transition={{
                repeat: Infinity,
                duration: 4
              }}
              className="
              absolute
              right-10
              bottom-0
              w-80
              bg-black/70
              backdrop-blur-xl
              border
              border-blue-500/20
              rounded-3xl
              p-8
              "
            >
              <p className="text-blue-400">
                RISK EVALUATION
              </p>

              <h3 className="text-5xl mt-4">
                A-
              </h3>

              <p className="text-gray-500 mt-3">
                Infrastructure stability score
              </p>
            </motion.div>

          </div>

        </div>

      </div>
    </section>
  );
}

export default DashboardPreview;